// packages/compiler/src/targets/codex.mjs -- Codex target: structurally the leanest of the
// three. Codex has NO per-role file format and NO command surface at all (confirmed against
// the installed `codex-shepherd@1.0.2` bundle -- discovery-d1-harness.md §Engineer follow-up:
// "No `prompts/`, no `commands/`, no `agents/`... Codex has nowhere to put one"). Roles
// compile into ONE `[agent_types]` TOML table mapping each role onto Codex's two native
// primitives (`explorer` read-only, `worker` write-capable), keyed off the hard
// `write_eligible` fact (content/RECONCILIATION.md §`write_eligible`), plus the declared
// `max_concurrent_children = 3` descendant cap (discovery-d1-harness.md, primary evidence
// from the live `shepherd.codex.toml`). Skills emit at the same relative `skills/` path
// Codex already uses.
//
// Root exclusion: RECONCILIATION.md row 4 states the installed table maps "8 shepherd
// roles," not 9 -- root only is excluded ("the table was never missing root, root was never
// a candidate"). `dispatchable: false` is NOT the right filter for this: `planter` is also
// `dispatchable: false` (meta-tier, never spawned by another shepherd role) yet the 8-role
// count requires it to remain IN the table. `model_hint: inherit-caller` is the fact unique
// to root (`shepherd` inherits the calling session rather than spawning a fresh one) and the
// only field content/roles/*.md carries that singles out exactly one role -- so it, not
// `dispatchable`, is this emitter's exclusion key.

import { emitSkillFile, shouldEmitSkillFor } from "../skill-emit.mjs";

const MAX_CONCURRENT_CHILDREN = 3;
const ROOT_MODEL_HINT = "inherit-caller";

/**
 * @param {{roles: import("../content.mjs").Role[], skills: import("../content.mjs").Skill[]}} content
 * @returns {import("../tree.mjs").EmittedFile[]}
 */
export function emitCodex({ roles, skills }) {
  const tableRoles = roles.filter((role) => role.modelHint !== ROOT_MODEL_HINT);
  const files = [emitAgentTypesConfig(tableRoles)];
  for (const skill of skills) {
    if (shouldEmitSkillFor("codex", skill)) files.push(emitSkillFile(skill));
  }
  return files;
}

function emitAgentTypesConfig(tableRoles) {
  const lines = [
    "# Generated by @fl03/compiler -- compile('codex'). Source: content/roles/*.md.",
    "# Do not hand-edit; regenerate via `node packages/compiler/bin/compile.mjs --target=codex`.",
    "",
    `max_concurrent_children = ${MAX_CONCURRENT_CHILDREN}`,
    "",
    "[agent_types]",
    ...tableRoles.map((role) => `${role.role} = "${role.writeEligible ? "worker" : "explorer"}"`),
    "",
  ];
  return {
    path: "shepherd.codex.toml",
    kind: "config",
    content: lines.join("\n"),
    sourcePath: "content/roles/*.md",
  };
}
