"""``shepherd insights`` — cross-lane INSIGHTS registry Typer sub-app.

Native port of ``skills/context/scripts/cmd_insights.sh`` (subcommands
``list|show|export|clear``), built on ``skills/context/scripts/_lib.sh``'s
``shctx_artifacts_root``/``shctx_now`` helpers. PURE FILESYSTEM, NO
DATABASE — insight records live as one JSON file per insight, at
``<workdir>/insights/<sprint>/<id>.json`` (``hooks/scripts/agent_insight_
capture.sh`` is the writer; this tool is read/prune-only). This module
never imports :mod:`shepherd_cli.db` or opens a Tortoise connection — there
is no table or view to mirror, so there is no sibling ``models_insights.py``
either (hard rule #8's "no Tortoise model for a pure file/raw-SQL command",
here specialized to "pure file", since there is no SQL at all).

WHY A SINGLE VARIADIC CALLBACK, NOT FOUR ``@app.command()``s
================================================================
``cmd_insights.sh`` is one ``case "$sub" in ... esac`` block whose parity
requirements don't match Typer/Click's own subcommand-dispatch defaults, in
the same way :mod:`shepherd_cli.commands.config` documents at length:

- **Default (empty) subcommand and ``-h``/``--help`` both print the usage
  blurb to STDOUT and exit 0** (``""|-h|--help) usage; exit 0 ;;``) — not
  Click's autogenerated help/error screen.
- **An unknown subcommand prints an ``ERROR: unknown subcommand: ...``
  line to STDERR, followed by the FULL usage text ALSO on stderr, and
  exits 1** (``*) echo ... >&2; usage >&2; exit 1 ;;``) — not Click's
  default "no such command" (exit 2).
- **Every subcommand's own arg loop rejects an unrecognized flag with
  ``ERROR: unknown arg: <token>`` on stderr and exit 1** — ``list``,
  ``export``, and ``clear`` all have this ``*) ... ;;`` default case in
  their per-token ``case`` statement. Click's own option parser would
  instead raise "no such option" (exit 2) for a flag it doesn't
  recognize, so every flag here is hand-parsed from a raw token list
  rather than declared as a ``typer.Option`` — the same technique
  :mod:`shepherd_cli.commands.search` and :mod:`shepherd_cli.commands.config`
  already use for the identical reason.
- **``show``'s own arg loop has NO default/unknown-arg case at all** — it
  only ever looks for a literal ``--json`` token among its remaining
  args and silently ignores anything else (see :func:`_cmd_show`'s
  docstring for the id-is-literally-``argv[0]`` quirk this implies).

So this module registers ZERO ``@app.command()``s and instead defines one
``@app.callback(invoke_without_command=True)`` that captures every token
after ``insights`` as a raw ``list[str]`` (via
``context_settings={"ignore_unknown_options": True}``, so a token like
``--json`` lands here as a literal string instead of Click trying, and
failing, to parse it as the callback's own option) and dispatches on
``argv[0]`` exactly like bash's ``case`` statement.

Timestamps: ``captured_at`` (an insight record field, read-only here) is
epoch-SECONDS, matching ``hooks/scripts/agent_insight_capture.sh``'s writer
and ``_lib.sh``'s ``shctx_now`` (``date +%s``). ``clear``'s own ``now``/
``cutoff`` computation uses ``int(time.time())`` for the same reason.
"""

from __future__ import annotations

import glob
import json
import os
import sys
import time
from collections import defaultdict
from datetime import datetime
from typing import Any

import typer
from pydantic import BaseModel, ConfigDict

from shepherd_cli.resolution import resolve_workdir

app = typer.Typer(
    add_completion=False,
    help="Cross-lane INSIGHTS registry: list, show, export, clear (bash: cmd_insights.sh).",
)

#: Verbatim bash-parity usage text — ``usage()`` in ``cmd_insights.sh``.
#: Printed to stdout on a bare/``-h``/``--help`` invocation and on
#: ``list``/``export``/``clear``'s own ``-h``/``--help`` token; printed to
#: stderr (after an ``ERROR:`` line) on an unknown top-level subcommand.
_USAGE = (
    "shctx insights <list|show|export|clear> [args]\n"
    "\n"
    "  list [--sprint=BRANCH] [--kind=K] [--actioned|--unactioned] [--json|--md]\n"
    "      Enumerate insights. Default: all sprints, all kinds, all states.\n"
    "      --sprint=BRANCH limits to one sprint dir.\n"
    "\n"
    "  show <id> [--json]\n"
    "      Render one insight record (assumes unique id across sprints).\n"
    "\n"
    "  export [--sprint=BRANCH] [--md]\n"
    "      Render as markdown for engineer mesh row 13 consumption.\n"
    "      Groups by kind, omits actioned items by default.\n"
    "\n"
    "  clear [--older-than-days=N]\n"
    "      Remove actioned insights older than N days (default 60).\n"
    "\n"
    "Schema: skills/adaptation/SKILL.md §INSIGHTS §V."
)

#: ``export``'s fixed kind-grouping order — ``cmd_insights.sh``'s
#: ``order = ["relocation","extension","duplication","consolidation","gap","nit"]``.
_EXPORT_KIND_ORDER: tuple[str, ...] = (
    "relocation",
    "extension",
    "duplication",
    "consolidation",
    "gap",
    "nit",
)

#: Plain-text ``list`` header, matching ``"{:<25}  {:<18}  {:<14}  {:<50}  {}"``
#: applied to the literal column names.
_TEXT_HEADER = "{:<25}  {:<18}  {:<14}  {:<50}  {}".format("ID", "SPRINT", "KIND", "SUBJECT", "ACTIONED")
_TEXT_RULE = "-" * 130


# --------------------------------------------------------------------------
# Pydantic schemas — parsed CLI option bundles, one per subcommand.
# --------------------------------------------------------------------------
class ListFilters(BaseModel):
    """Parsed ``shctx insights list`` flags.

    Deliberately does NOT model an insight *record* itself (``sprint``,
    ``kind``, ``subject``, ...) — those are read and rendered as raw
    ``dict[str, Any]`` throughout this module (see :func:`_load_records`'s
    docstring for why), so a strict Pydantic model of the on-disk JSON
    shape would either lose the loose ``.get(key, default)``-vs-``r[key]``
    distinction ``cmd_insights.sh``'s own inline Python renderers rely on,
    or have to reimplement it awkwardly. This model instead captures the
    already-unambiguous, already-validated CLI *inputs*.

    Attributes:
        sprint: ``--sprint=BRANCH`` value, or ``""`` for "all sprints".
        kind: ``--kind=K`` value, or ``""`` for "all kinds".
        want_actioned: ``True`` after ``--actioned``, ``False`` after
            ``--unactioned``, ``None`` if neither was given (bash: the
            empty-string ``want_actioned`` sentinel). The last of
            ``--actioned``/``--unactioned`` on the command line wins.
        fmt: ``"text"`` (default), ``"json"``, or ``"md"`` — the last of
            ``--json``/``--md`` on the command line wins.
    """

    model_config = ConfigDict(frozen=True)

    sprint: str = ""
    kind: str = ""
    want_actioned: bool | None = None
    fmt: str = "text"


class ExportFilters(BaseModel):
    """Parsed ``shctx insights export`` flags.

    Attributes:
        sprint: ``--sprint=BRANCH`` value, or ``""`` for "all sprints".
    """

    model_config = ConfigDict(frozen=True)

    sprint: str = ""


class ClearOptions(BaseModel):
    """Parsed ``shctx insights clear`` flags.

    Attributes:
        days_raw: The raw, UNPARSED ``--older-than-days=N`` string
            (default ``"60"``). Kept as a string (not an ``int``) because
            bash's own ``clear`` prints this value back verbatim in its
            final summary line without ever reassigning it — only the
            derived ``cutoff`` arithmetic parses it numerically. See
            :func:`_cmd_clear`.
    """

    model_config = ConfigDict(frozen=True)

    days_raw: str = "60"


# --------------------------------------------------------------------------
# Store location + record loading.
# --------------------------------------------------------------------------
def _insights_root() -> str:
    """Resolve the insights store root: ``<workdir>/insights``.

    Bash parity with ``cmd_insights.sh``'s ``_insights_root``: ``"$(shctx_
    artifacts_root)/insights"``, i.e. :func:`shepherd_cli.resolution.
    resolve_workdir` plus a literal ``/insights`` suffix (plain string
    concatenation, matching bash's own ``"$root/insights"`` — not
    ``os.path.join``, though the two are equivalent here since
    ``resolve_workdir()`` never returns a trailing slash).

    Returns:
        The insights store root path (need not exist on disk).
    """
    return f"{resolve_workdir()}/insights"


def _load_records(files: list[str]) -> list[dict[str, Any]]:
    """Load every insight JSON file, silently skipping unparseable ones.

    Bash parity with the inline Python ``list``/``export`` renderers'
    identical ``try: r = json.load(open(p)) except Exception: continue``
    loop — a corrupt or non-JSON file in the insights tree is dropped from
    the result set rather than aborting the command. (``show``/``clear``
    do NOT have this guard in bash — see their own functions for why a
    malformed record there is allowed to raise instead.)

    Args:
        files: Insight JSON file paths to load, in the order they should
            appear in the (pre-sort) result list.

    Returns:
        The successfully-parsed records, as raw ``dict``s (NOT validated
        against any schema — every renderer reproduces bash's own
        ``.get(key, default)``/``r[key]`` field-access quirks directly
        against these dicts).
    """
    rows: list[dict[str, Any]] = []
    for path in files:
        try:
            with open(path, encoding="utf-8") as fh:
                rows.append(json.load(fh))
        except Exception:  # noqa: BLE001 - bash parity: any load failure just skips the file
            continue
    return rows


def _sprint_files(root: str, sprint: str) -> list[str] | None:
    """Glob every ``*.json`` file directly under one sprint directory.

    Args:
        root: The insights store root (see :func:`_insights_root`).
        sprint: The sprint branch name (a subdirectory of ``root``).

    Returns:
        The sorted file list (bash-parity: bash's default glob expansion
        sorts matches lexicographically), or ``None`` if ``root/sprint``
        is not a directory — the caller distinguishes this from "directory
        exists but is empty" (bash: ``[[ -d "$root/$sprint" ]] || { echo
        "No insights for sprint $sprint."; exit 0; }``, checked BEFORE the
        glob, not folded into an empty-list result).
    """
    sprint_dir = os.path.join(root, sprint)
    if not os.path.isdir(sprint_dir):
        return None
    return sorted(glob.glob(os.path.join(sprint_dir, "*.json")))


def _all_files(root: str) -> list[str]:
    """Glob every ``*.json`` file one level under every sprint directory.

    Args:
        root: The insights store root.

    Returns:
        The sorted file list across all sprint subdirectories (bash:
        ``for f in "$root"/*/*.json``).
    """
    return sorted(glob.glob(os.path.join(root, "*", "*.json")))


# --------------------------------------------------------------------------
# list.
# --------------------------------------------------------------------------
def _render_list_text(rows: list[dict[str, Any]]) -> str:
    """Render ``list``'s default plain-text, fixed-width table.

    Bash parity with the inline Python's ``else`` (text) branch, column
    for column: ``r["id"]`` is accessed with a bare subscript (raises
    ``KeyError`` if a loaded record has no ``id`` — preserved, not
    guarded), while every other field uses ``.get(key, default)``.

    Args:
        rows: Filtered, sorted records, as raw dicts.

    Returns:
        The header line, the ``-`` * 130 rule, then one row per record —
        joined with ``"\\n"`` (no trailing newline; the caller's
        ``typer.echo`` supplies exactly one).
    """
    lines = [_TEXT_HEADER, _TEXT_RULE]
    for r in rows:
        actioned = "yes ({})".format(r.get("actioned_in") or "") if r.get("actioned") else "no"
        lines.append(
            "{:<25}  {:<18}  {:<14}  {:<50}  {}".format(
                r["id"][:25],
                (r.get("sprint", "") or "")[:18],
                r.get("kind", ""),
                (r.get("subject", "") or "")[:50],
                actioned,
            )
        )
    return "\n".join(lines)


def _render_list_md(rows: list[dict[str, Any]]) -> str:
    """Render ``list --md``'s markdown table.

    Bash parity with the inline Python's ``if fmt == "md"`` branch: note
    ``r.get("subject","")[:60]`` here is NOT wrapped in ``... or ""``
    (unlike the text renderer's ``subject`` column) — a record whose
    ``subject`` key is present but explicitly ``null`` raises
    ``TypeError`` (``NoneType`` has no ``__getitem__`` slice), preserved
    exactly rather than defensively coerced.

    Args:
        rows: Filtered, sorted records, as raw dicts.

    Returns:
        The markdown table (header + separator + one row per record), no
        trailing newline.
    """
    lines = ["| ID | Sprint | Kind | Subject | Actioned |", "|---|---|---|---|---|"]
    for r in rows:
        actioned = "✓ " + (r.get("actioned_in") or "") if r.get("actioned") else "—"
        lines.append(
            "| `{}` | {} | {} | {} | {} |".format(
                r["id"], r.get("sprint", ""), r.get("kind", ""), r.get("subject", "")[:60], actioned
            )
        )
    return "\n".join(lines)


def _cmd_list(tokens: list[str]) -> int:
    """Implement ``shctx insights list``.

    Bash parity with ``_cmd_list`` in ``cmd_insights.sh``: per-token flag
    parsing (unknown token -> stderr error, exit 1), then a three-tier
    "nothing to show" ladder (no store at all -> no matching sprint dir ->
    no files after globbing), then filter + sort + render.

    Args:
        tokens: Every token after ``list``, in order.

    Returns:
        The bash-parity process exit code.
    """
    sprint = ""
    kind = ""
    want_actioned: bool | None = None
    fmt = "text"

    for arg in tokens:
        if arg.startswith("--sprint="):
            sprint = arg[len("--sprint=") :]
        elif arg.startswith("--kind="):
            kind = arg[len("--kind=") :]
        elif arg == "--actioned":
            want_actioned = True
        elif arg == "--unactioned":
            want_actioned = False
        elif arg == "--json":
            fmt = "json"
        elif arg == "--md":
            fmt = "md"
        elif arg in ("-h", "--help"):
            typer.echo(_USAGE)
            return 0
        else:
            typer.echo(f"ERROR: unknown arg: {arg}", err=True)
            return 1

    filters = ListFilters(sprint=sprint, kind=kind, want_actioned=want_actioned, fmt=fmt)

    root = _insights_root()
    if not os.path.isdir(root):
        typer.echo("No insights recorded yet.")
        return 0

    if filters.sprint:
        files = _sprint_files(root, filters.sprint)
        if files is None:
            typer.echo(f"No insights for sprint {filters.sprint}.")
            return 0
    else:
        files = _all_files(root)

    if not files:
        typer.echo("No insight records.")
        return 0

    rows = _load_records(files)
    if filters.kind:
        rows = [r for r in rows if r.get("kind") == filters.kind]
    if filters.want_actioned is True:
        rows = [r for r in rows if r.get("actioned")]
    elif filters.want_actioned is False:
        rows = [r for r in rows if not r.get("actioned")]
    rows.sort(key=lambda r: r.get("captured_at", 0), reverse=True)

    if filters.fmt == "json":
        typer.echo(json.dumps(rows, indent=2))
        return 0

    if not rows:
        typer.echo("(no insights match the filters)")
        return 0

    if filters.fmt == "md":
        typer.echo(_render_list_md(rows))
    else:
        typer.echo(_render_list_text(rows))
    return 0


# --------------------------------------------------------------------------
# show.
# --------------------------------------------------------------------------
def _render_show_text(r: dict[str, Any]) -> str:
    """Render ``show``'s default plain-text single-record view.

    Bash parity with the inline Python renderer, field for field —
    including its inconsistent defaulting: ``r.get("id","?")`` and
    ``r.get("kind","?")`` fall back only when the key is MISSING (a
    present-but-``null`` value is concatenated as ``None``, raising
    ``TypeError``, preserved), while ``r.get("sprint") or "?"``,
    ``r.get("subject") or ""``, ``r.get("observation") or ""``, and
    ``r.get("rationale") or ""`` also fall back on an explicit ``null``
    value. ``captured_at`` is read via the bare ``r.get("captured_at",0)``
    (missing -> epoch 0; present-but-``null`` -> ``TypeError`` from
    ``datetime.fromtimestamp(None)``, also preserved).

    Args:
        r: The single loaded insight record.

    Returns:
        The multi-line report, no trailing newline.
    """
    ts = datetime.fromtimestamp(r.get("captured_at", 0)).isoformat(timespec="seconds")
    lines = [
        "Insight:      " + r.get("id", "?"),
        "Sprint:       " + (r.get("sprint") or "?"),
        "Captured at:  " + ts,
        "Kind:         " + r.get("kind", "?"),
        "Actioned:     "
        + ("yes (in " + (r.get("actioned_in") or "?") + ")" if r.get("actioned") else "no"),
        "",
        "Subject:",
        "  " + (r.get("subject") or ""),
        "Observation:",
        "  " + (r.get("observation") or ""),
        "Rationale:",
        "  " + (r.get("rationale") or ""),
    ]
    return "\n".join(lines)


def _cmd_show(tokens: list[str]) -> int:
    """Implement ``shctx insights show <id> [--json]``.

    Bash parity with ``_cmd_show``: the id is ``argv[0]`` TAKEN
    LITERALLY, whatever it looks like — ``shctx insights show --json``
    treats ``"--json"`` itself as the id (and, having consumed it, the
    REMAINING args loop then has nothing left to find a ``--json`` flag
    in, so the text renderer runs). Every token after the id is scanned
    for a literal ``--json``; unlike ``list``/``export``/``clear``, there
    is NO unknown-arg rejection here at all — any other token (including
    ``-h``/``--help``) is silently ignored, matching bash's ``case "$arg"
    in --json) fmt="json" ;; esac`` (no default arm).

    ``--json`` prints the matched file's RAW BYTES verbatim (bash: ``cat
    "$match"``) — not a re-serialized ``json.dumps`` of the parsed
    content — so this reproduces the source file's exact formatting,
    whitespace, key order, and trailing-newline-or-not byte for byte.

    Args:
        tokens: Every token after ``show``, in order. ``tokens[0]`` (if
            present) is the id; every remaining token is scanned for
            ``--json``.

    Returns:
        1 (stderr usage message) if no id was given. 2 (stderr "not
        found" message) if no ``<root>/*/<id>.json`` file exists. 0 on a
        successful render (either format).
    """
    insight_id = tokens[0] if tokens else ""
    if not insight_id:
        typer.echo("ERROR: usage: shctx insights show <id>", err=True)
        return 1

    fmt = "text"
    for arg in tokens[1:]:
        if arg == "--json":
            fmt = "json"

    root = _insights_root()
    match: str | None = None
    for path in sorted(glob.glob(os.path.join(root, "*", f"{insight_id}.json"))):
        if os.path.isfile(path):
            match = path
            break
    if match is None:
        typer.echo(f"ERROR: insight {insight_id} not found", err=True)
        return 2

    if fmt == "json":
        with open(match, encoding="utf-8") as fh:
            content = fh.read()
        sys.stdout.write(content)
        return 0

    with open(match, encoding="utf-8") as fh:
        record = json.load(fh)
    typer.echo(_render_show_text(record))
    return 0


# --------------------------------------------------------------------------
# export.
# --------------------------------------------------------------------------
def _render_export(sprint: str, files: list[str]) -> str:
    """Render ``export``'s markdown report, grouped by kind.

    Bash parity with the inline Python renderer: records are loaded here
    (not via :func:`_load_records`, since a corrupt file is skipped with
    the SAME bare ``try/except: continue`` bash uses, but grouping and
    actioned-filtering happen in the same pass, matching bash's single
    combined loop); actioned records are dropped entirely (``export``
    never shows them); groups are emitted in :data:`_EXPORT_KIND_ORDER`,
    skipping any kind with zero (unactioned) records; within a group,
    records are sorted by ``captured_at`` ASCENDING (oldest first — the
    opposite of ``list``'s descending sort).

    Args:
        sprint: The ``--sprint`` filter value (``""`` for "all sprints"),
            used only for the report's header label.
        files: The insight JSON file paths to consider.

    Returns:
        The full markdown report, no trailing newline.
    """
    groups: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for path in files:
        try:
            with open(path, encoding="utf-8") as fh:
                r = json.load(fh)
        except Exception:  # noqa: BLE001 - bash parity: a corrupt file is skipped, not fatal
            continue
        if r.get("actioned"):
            continue
        groups[r.get("kind", "gap")].append(r)

    label = sprint if sprint else "all sprints"
    lines = [f"## Cross-lane insights — {label}", ""]
    seen_any = False
    for kind in _EXPORT_KIND_ORDER:
        items = groups.get(kind, [])
        if not items:
            continue
        seen_any = True
        lines.append(f"### {kind} ({len(items)})")
        lines.append("")
        for r in sorted(items, key=lambda x: x.get("captured_at", 0)):
            lines.append(f"- **{r.get('subject', '?')}**  _(sprint: {r.get('sprint', '?')}, id: `{r['id']}`)_")
            if r.get("observation"):
                lines.append(f"  - observation: {r['observation']}")
            if r.get("rationale"):
                lines.append(f"  - rationale:   {r['rationale']}")
        lines.append("")
    if not seen_any:
        lines.append("_(no unactioned insights)_")
    return "\n".join(lines)


def _cmd_export(tokens: list[str]) -> int:
    """Implement ``shctx insights export [--sprint=BRANCH] [--md]``.

    Bash parity with ``_cmd_export``: identical flag-loop shape to
    :func:`_cmd_list` (unknown token -> stderr error, exit 1), but ``fmt``
    is always ``"md"`` in practice — ``--md`` is accepted (and is the only
    format flag bash offers here; there is no ``--json`` for ``export``)
    but is a no-op since ``"md"`` is already the default and the only
    rendering path this command has.

    Args:
        tokens: Every token after ``export``, in order.

    Returns:
        The bash-parity process exit code.
    """
    sprint = ""
    for arg in tokens:
        if arg.startswith("--sprint="):
            sprint = arg[len("--sprint=") :]
        elif arg == "--md":
            pass
        elif arg in ("-h", "--help"):
            typer.echo(_USAGE)
            return 0
        else:
            typer.echo(f"ERROR: unknown arg: {arg}", err=True)
            return 1

    filters = ExportFilters(sprint=sprint)

    root = _insights_root()
    if not os.path.isdir(root):
        typer.echo("(no insights)")
        return 0

    if filters.sprint:
        files = _sprint_files(root, filters.sprint)
        if files is None:
            typer.echo(f"(no insights for {filters.sprint})")
            return 0
    else:
        files = _all_files(root)

    if not files:
        typer.echo("(no insight records)")
        return 0

    typer.echo(_render_export(filters.sprint, files))
    return 0


# --------------------------------------------------------------------------
# clear.
# --------------------------------------------------------------------------
def _cmd_clear(tokens: list[str]) -> int:
    """Implement ``shctx insights clear [--older-than-days=N]``.

    Bash parity with ``_cmd_clear``: an actioned record is removed once
    its ``captured_at`` predates ``now - days*86400``; an unactioned
    record (or one with no ``captured_at`` at all, per the ``or 0``
    fallback) is always kept.

    Args:
        tokens: Every token after ``clear``, in order.

    Returns:
        The bash-parity process exit code.

    Raises:
        Nothing directly; a malformed insight JSON file encountered while
        scanning raises the underlying :class:`json.JSONDecodeError` (or
        :class:`OSError`) UNCAUGHT — bash parity: ``_cmd_clear``'s inline
        Python has no ``try/except`` around its own ``json.load``, so a
        corrupt file already aborts the whole ``shctx insights clear``
        invocation with a non-zero exit under ``set -e``, unlike ``list``/
        ``export``'s deliberately lenient loaders.

    Note (documented deviation — non-integer ``--older-than-days``):
        Bash's ``cutoff=$(( now - days * 86400 ))`` arithmetic expansion
        aborts the whole script (via ``set -e``) with bash's own
        uncontrolled error text if ``days`` is not a value bash's
        arithmetic parser accepts. This port instead raises a controlled
        stderr message and exits 1 — the same class of deviation
        :mod:`shepherd_cli.commands.search`'s ``_parse_limit`` documents
        for the identical reason. The final summary line prints the raw
        ``--older-than-days`` STRING (``days_raw``), not the parsed
        ``int``, matching bash's own ``$days`` (never reassigned after
        arg-parsing) verbatim — so e.g. ``--older-than-days=007`` reports
        "007 days" in the summary even though the cutoff arithmetic used
        the value 7.
    """
    days_raw = "60"
    for arg in tokens:
        if arg.startswith("--older-than-days="):
            days_raw = arg[len("--older-than-days=") :]
        elif arg in ("-h", "--help"):
            typer.echo(_USAGE)
            return 0
        else:
            typer.echo(f"ERROR: unknown arg: {arg}", err=True)
            return 1

    options = ClearOptions(days_raw=days_raw)

    root = _insights_root()
    if not os.path.isdir(root):
        typer.echo("(nothing to clear)")
        return 0

    try:
        days = int(options.days_raw)
    except ValueError:
        typer.echo(f"ERROR: --older-than-days must be an integer, got: {options.days_raw}", err=True)
        return 1

    now = int(time.time())
    cutoff = now - days * 86400
    removed = 0
    for path in _all_files(root):
        with open(path, encoding="utf-8") as fh:
            r = json.load(fh)
        keep = (not r.get("actioned")) or ((r.get("captured_at") or 0) >= cutoff)
        if not keep:
            os.remove(path)
            removed += 1

    typer.echo(f"Removed {removed} actioned insight(s) older than {options.days_raw} days.")
    return 0


# --------------------------------------------------------------------------
# Dispatcher + Typer wiring.
# --------------------------------------------------------------------------
def _dispatch(argv: list[str]) -> int:
    """Dispatch on ``argv[0]`` exactly like ``cmd_insights.sh``'s ``case`` statement.

    Args:
        argv: The raw remaining command-line tokens after ``insights``,
            e.g. ``["list", "--json"]`` or ``[]``.

    Returns:
        The bash-parity process exit code for whichever subcommand ran
        (or the bare/help/unknown-subcommand arms).
    """
    sub = argv[0] if argv else ""
    rest = argv[1:]

    if sub == "list":
        return _cmd_list(rest)
    if sub == "show":
        return _cmd_show(rest)
    if sub == "export":
        return _cmd_export(rest)
    if sub == "clear":
        return _cmd_clear(rest)
    if sub in ("", "-h", "--help"):
        typer.echo(_USAGE)
        return 0

    typer.echo(f"ERROR: unknown subcommand: {sub}", err=True)
    typer.echo(_USAGE, err=True)
    return 1


@app.callback(invoke_without_command=True, context_settings={"ignore_unknown_options": True, "help_option_names": []})
def insights(
    args: list[str] = typer.Argument(
        None,
        help=(
            "Subcommand + args: 'list [--sprint=B] [--kind=K] [--actioned|--unactioned] "
            "[--json|--md]' | 'show <id> [--json]' | 'export [--sprint=B] [--md]' | "
            "'clear [--older-than-days=N]'. Defaults to usage/help."
        ),
    ),
) -> None:
    """Cross-lane INSIGHTS registry — native port of ``shctx insights``.

    See the module docstring for why this is ONE variadic callback rather
    than four ``@app.command()``s: bash's default-to-usage, exit-1-on-
    unknown-subcommand, and per-subcommand-``ERROR:-unknown-arg`` contracts
    don't match Typer/Click's own subcommand-dispatch defaults.

    Args:
        args: Every token after ``insights`` on the command line, in
            order, with NOTHING pre-parsed as flags/options by Click (see
            ``context_settings={"ignore_unknown_options": True}`` on this
            callback). ``None``/empty means a bare ``shepherd insights`` —
            dispatched as the usage/help arm, per bash's ``""|-h|--help)
            usage; exit 0 ;;``.
    """
    raise typer.Exit(code=_dispatch(list(args or [])))


__all__ = ["app", "ListFilters", "ExportFilters", "ClearOptions"]
